.Dd Feb 03 2024
.Dt md2mdoc 7
.Os
.Au John Kaul
.Pp
.Sh NAME
.Nm md2mdoc 
.Nd a simple markdown to mdoc converter.
.Pp
.Sh SYNOPSIS
md2mdoc <input MDfile> <output MDOCfile>
.Pp
.Sh DESCRIPTION
This utility will convert simple markdown syntax characters to mdoc
(man page) format characters. It will remove all leading spaces from
lines unless within a code block.
.Pp
This utility is not intelligent at all, it will give wonky results if
confused but it does offer a very good staring point for creating man
page documentation for your project.
.Pp
The use of this utility is intended to offer a way to keep project
notes/documention in a simple markdown format (plain text) where large
sections can be added/deleted easier. When the time comes to create
more formal documentaiton, this utility aids in that process (assuming
your markdown isn't too complicated).
.Pp
.Sh CHARACTER CONVERSION TABLE
.Pp
.Bd -literal -offset indent
    #           ->  .Sh     : section headers
    # NAME      ->          : md2mdoc will assume the next line will
                              be a name and a description. This should
                              be formatted as the example below.
    blank line  ->  .Pp     : Blank Line
    -<char>     ->  .It Fl  : List element
    -           ->  .El     : A single dash is assumed to be a `list end`.
    ~           ->  .El     : An alternate `list end` character.
    <           ->  .nf     : Start of a `no format` block.
    >           ->  .fi     : End of a `no format` block.
    ```         ->  .nf     : Start/End of a `no format` block.
    *           ->  .Bf     : Bold
    _           ->  .Em     : Italic
    ^           ->  .Sx     : Reference
    [           ->  .Op     : Optional argument
    author:     ->  .Au     : Author
    date:       ->  .Dd     : Date
    title:      ->  .Dt .Os : Document title with section number. See
                              manual section numbers and example below.
   <!--         ->          : Start of a comment block.
   -->          ->          : End of a comment block.
.Ed
.Pp
.Sh SAMPLE MARKDOWN EXAMPLE
.Pp
.Bd -literal -offset indent
    <!--
        This is a comment block and should be ignored.
    -->
    date: Feb 03 2024
    title: progname 7
    author: John Kaul
.Pp
    # NAME
    progname -- a program to change the world.
.Pp
    # SYNOPSIS
    progname 
    [-abc]
    <inpputfile> 
    <outputfile>
.Pp
    # DESCRIPTION
    This utility will change the world because
    it will remove all leading spaces from lines
    in a text file.
.Pp
    # OPTIONS
    -a
        Append to the outout file.
.Pp
    -B
        Use backward searching patterns (?...?).
.Pp
    -d
        Parse `#defines` that don't take arguments.
    -
.Pp
    # CODE EXAMPLE
    ```c
        unsigned long   str_version;    /* version number */
        unsigned long   str_numstr;     /* # of strings in the file */
        unsigned long   str_longlen;    /* length of longest string */
    ```
.Pp
    *WARNING*
        Never do the above.
    
    _NOTE_
        This is a note block.
    
    # SEE ALSO
    ^md2mdoc(7)^
    ^this^
    ^that^
    ^theotherthing^
.Ed
.Pp
.Em NOTE
All the symbols this program finds are located at the beginning of
the line. -i.e. This program is not good at parsing the entire
strings looking for symbols.
.Pp
.Pp
.Sh MANUAL SECTIONS
The standard sections for man pages:
.Bd -literal -offset indent
       1      User Commands
       2      System Calls
       3      C Library Functions
       4      Devices and Special Files
       5      File Formats and Conventions
       6      Games et. Al.
       7      Miscellanea
       8      System Administration tools and Deamons
.Ed
.Pp
.Sh MARKDOWN COMMENTS
A comments style header can be kept in the markdown file which md2mdoc
will ignore during processing. The comment style is HTML Tag style
which is also ignored in other markdown processors.
.Pp
.Sh SEE ALSO
.Sx mdoc(7)
.Sx mandoc(1)
.Sx man(1)
.Pp
.Sh HISTORY
Created for my personal use.
.Pp
.Sh AUTHOR
John Kaul
