.\" Copyright (c) 2026 John Kaul
.\" SPDX-License-Identifier: BSD-2-Clause
.Dd Feb 02 2026
.Dt md2mdoc 7
.Os
.Au John Kaul
.Pp
.Sh NAME
.Nm md2mdoc 
.Nd a simple markdown to mdoc converter.
.Pp
.Sh SYNOPSIS
.Nm
.Op Fl o Ar outputfile
inputfile
.Pp
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl o Ar outputfile
A mandoc file to write.
.Pp
.It inputfile
A file written in the markdown syntax outlined below.
.El
.Pp
.Sh DESCRIPTION
This utility will convert simple markdown syntax characters to mdoc
(man page) format characters. It will remove all leading spaces from
lines unless within a code block. It will print to 
.Li stdout
unless
specified otherwise.
.Pp
This utility is not intelligent at all, it will give wonky results if
confused but it does offer a very good staring point for creating man
page documentation for your project.
.Pp
The use of this utility is intended to offer a way to keep project
notes/documentation in a simple markdown format (plain text) where large
sections can be added/deleted easier. When the time comes to create
more formal documentation, this utility aids in that process (assuming
your markdown isn't too complicated).
.Pp
.Sh CHARACTER CONVERSION TABLE
.Pp
.Bd -literal -offset indent
    #           ->  .Sh     : section headers
    # NAME      ->          : md2mdoc will assume the next line will
                              be a name and a description. This should
                              be formatted as the example below.
    blank line  ->  .Pp     : Blank Line
    - <string>  ->  .It     : List item.
    -<char>     ->  .It Fl  : List element and a space after the <char>
                              is assumed to be an argument to the flag.
    EXAMPLE:
      -<char>          ->  .It Fl <char>
      -<char> <string> ->  .It Fl <char> Ar <string>
      - <string>       ->  .It <string>
.Pp
    -           ->  .El     : A single dash--followed by a newline--is
                              assumed to be a `list end`.
    ~           ->  .El     : An alternate `list end` character.
    <           ->  .nf     : Start of a `no format` block.
    >           ->  .fi     : End of a `no format` block.
    ```         ->  .nf     : Start/End of a `no format` block.
    `           ->  .Li     : Literal
    *           ->  .Bf     : Bold
    _           ->  .Em     : Italic
    ^           ->  .Sx     : Reference
    [           ->  .Op     : Optional argument
    author:     ->  .Au     : Author
    date:       ->  .Dd     : Date
    title:      ->  .Dt .Os : Document title with section number. See
                              manual section numbers and example below.
   <!--         ->          : Start of a comment block.
   -->          ->          : End of a comment block.
.Ed
.Pp
.Sh SAMPLE MARKDOWN EXAMPLE
.Pp
.Bd -literal -offset indent
    <!--
        This is a markdown comment block and should be ignored
        (i.e. not added to mdoc file).
    -->
    date: Feb 03 2024
    title: progname 7
    author: John Kaul
.Pp
    .\\\\\\" Copyright (c) <year> <who>
    .\\\\\\" SPDX-License-Identifier: BSD-2-Clause
.Pp
    # NAME
    progname -- a program to change the world.
.Pp
    # SYNOPSIS
    progname
    [-abc]
    [-f file]
    inpputfile
    outputfile
.Pp
    # DESCRIPTION
    This utility will change the world because
    it will remove all leading spaces from lines
    in a text file.
.Pp
    A backslash (\) will escape a formatting character
    like this: \\*this will not be bold\\*.
.Pp
    # OPTIONS
    -a
        Append to the outout file.
.Pp
    -B
        Use backward searching patterns (?...?).
.Pp
    -d
        Parse `#defines` that don't take arguments.
.Pp
    -f file
        Pass a file argument to this option.
.Pp
    - inputfile
        The file to pass as an input.
.Pp
    - outputfile
        The file to write.
.Pp
    -
.Pp
    # CODE EXAMPLE
    ```c
        unsigned long   str_version;    /* version number */
        unsigned long   str_numstr;     /* # of strings in the file */
        unsigned long   str_longlen;    /* length of longest string */
    ```
.Pp
    *WARNING:*
        Never do the above.
.Pp
    _NOTE:_
        This is a note block.
.Pp
    # SEE ALSO
    ^md2mdoc(7)^, ^this(7)^, ^that(7)^, ^theotherthing(7)^
.Ed
.Pp
.Pp
.Em NOTE:
Most symbols will naturally occur at the start of a line (header,
code block, etc.) but a few items like *bold*, _italic_,
`literal`, and ^refernces^, can be nested within the text.
.Pp
.Sh MANUAL SECTIONS
The standard sections for man pages:
.Bd -literal -offset indent
       1      User Commands
       2      System Calls
       3      C Library Functions
       4      Devices and Special Files
       5      File Formats and Conventions
       6      Games et. Al.
       7      Miscellanea
       8      System Administration tools and Deamons
.Ed
.Pp
.Sh MARKDOWN COMMENTS
A comments style header can be kept in the markdown file which 
.Nm
will
ignore during processing. The comment style is HTML Tag style which is also
ignored in other markdown processors.
.Pp
.Sh EXAMPLES
Create an 'output' mandoc file from markdown 'input':
.Bd -literal -offset indent
    % md2mdoc -o output input
.Ed
.Pp
Create an 'output' mandoc file from markdown 'input' via redirect:
.Bd -literal -offset indent
    % md2mdoc input > output
.Ed
.Pp
Pipe a markdown file 'input' to 
.Xr mandoc 1  
for processing on the fly:
.Bd -literal -offset indent
    % md2mdoc input | mandoc -mdoc
.Ed
.Pp
.Sh SEE ALSO
.Xr mdoc 7 , 
.Xr mandoc 1 , 
.Xr man 1 
.Pp
.Sh HISTORY
Created for my personal use.
.Pp
.Sh AUTHOR
John Kaul
